// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoOmGf9ZekDv4ixAWwKiw6Mq00-LibwTk',
    appId: '1:711051349637:web:b9dc38703b8e3347e923ec',
    messagingSenderId: '711051349637',
    projectId: 'e-commerce-flutter-vku',
    authDomain: 'e-commerce-flutter-vku.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-vku.appspot.com',
    measurementId: 'G-1W2QMTWPN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWewl5iTsSqbqDxTUYigpTyYMw3k_OqfA',
    appId: '1:711051349637:android:228617b45f1c5996e923ec',
    messagingSenderId: '711051349637',
    projectId: 'e-commerce-flutter-vku',
    storageBucket: 'e-commerce-flutter-vku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGn6LWIJ6PqIgvPEhUOtIpxfxse7EmAuE',
    appId: '1:711051349637:ios:067d853b3bccd8dde923ec',
    messagingSenderId: '711051349637',
    projectId: 'e-commerce-flutter-vku',
    storageBucket: 'e-commerce-flutter-vku.appspot.com',
    iosClientId: '711051349637-1a7m68ef8uq62klltuqqftvf5ta7g6ch.apps.googleusercontent.com',
    iosBundleId: 'vn.hvloan.eCommerceApp',
  );
}
